export const data = [
  {
    id: 1,
    img: '/users/joao.png',
    nickname: 'João',
    name: 'João Faria',
    birthdate: 'Mar 5, 2005',
    gender: 'Masculine',
    bloodType: 'A+',
    location: 'Gateway',
    ecgBpm: 68,
    spo2: 99,
    systolic: 115,
    diastolic: 79,
    etco2: 4,
    respiratoryRate: 13,
    bodyTemperature: 37.9,
    glucoseLevel: 100,
    mentalStage: {
      percentage: 98,
      sleep: 'Sleep well',
      cognitivePerformance: 'Normal'
    }
  },
  {
    id: 2,
    img: '/users/ana.png',
    nickname: 'Ana',
    name: 'Ana Ataya',
    birthdate: 'Feb 18, 2006',
    gender: 'Feminine',
    bloodType: 'O+',
    location: 'Gateway',
    ecgBpm: 87,
    spo2: 100,
    systolic: 120,
    diastolic: 78,
    etco2: 5,
    respiratoryRate: 15,
    bodyTemperature: 38,
    glucoseLevel: 90,
    mentalStage: {
      percentage: 95,
      sleep: 'Sleep well',
      cognitivePerformance: 'Normal'
    }
  },
  {
    id: 3,
    img: '/users/joana.png',
    nickname: 'Joana',
    name: 'Joana Mendes',
    birthdate: 'Jun 31, 2004',
    gender: 'Feminine',
    bloodType: 'O+',
    location: 'Lunar module',
    ecgBpm: 84,
    spo2: 100,
    systolic: 115,
    diastolic: 76,
    etco2: 4,
    respiratoryRate: 13,
    bodyTemperature: 37.7,
    glucoseLevel: 80,
    mentalStage: {
      percentage: 95,
      sleep: 'Sleep well',
      cognitivePerformance: 'Normal'
    }
  },
  {
    id: 4,
    img: '/users/rita.png',
    nickname: 'Rita',
    name: 'Ana Rita Pires',
    birthdate: 'Jun 6, 2002',
    gender: 'Feminine',
    bloodType: 'A+',
    location: 'Com. Room',
    ecgBpm: 85,
    spo2: 100,
    systolic: 110,
    diastolic: 80,
    etco2: 4,
    respiratoryRate: 14,
    bodyTemperature: 37.2,
    glucoseLevel: 85,
    mentalStage: {
      percentage: 65,
      sleep: 'Very restless night',
      cognitivePerformance: 'Pending assessment'
    },
    medicalRecord: ["Adaptative Microgravity Syndrome", "Shellfish allergy"]
  },
  {
    id: 5,
    img: '/users/diogo.png',
    nickname: 'Diogo',
    name: 'Diogo Azevedo',
    birthdate: 'Jun 20, 2004',
    gender: 'Masculine',
    bloodType: 'B+',
    location: 'Living room',
    ecgBpm: 90,
    spo2: 100,
    systolic: 122,
    diastolic: 75,
    etco2: 4,
    respiratoryRate: 14,
    bodyTemperature: 37,
    glucoseLevel: 80,
    mentalStage: {
      percentage: 100,
      sleep: 'Sleep well',
      cognitivePerformance: 'Normal'
    }
  },
  {
    id: 6,
    img: '/users/adriano.png',
    nickname: 'Adriano',
    name: 'Adriano Vilhena',
    birthdate: 'Oct 11, 2008',
    gender: 'Masculine',
    bloodType: 'O-',
    location: 'Living room',
    ecgBpm: 80,
    spo2: 100,
    systolic: 115,
    diastolic: 71,
    etco2: 4,
    respiratoryRate: 17,
    bodyTemperature: 37,
    glucoseLevel: 80,
    mentalStage: {
      percentage: 85,
      sleep: 'Took longer to fall asleep',
      cognitivePerformance: 'Normal'
    },
    medicalRecord: ["Asthma", "Allergic to dust mites"]
  },
  {
    id: 7,
    img: '/users/caio.png',
    nickname: 'Caio',
    name: 'Caio Romanichen',
    birthdate: 'Apr 4, 2002',
    gender: 'Masculine',
    bloodType: 'A+',
    location: 'Living room',
    ecgBpm: 75,
    spo2: 100,
    systolic: 112,
    diastolic: 75,
    etco2: 4,
    respiratoryRate: 15,
    bodyTemperature: 37.5,
    glucoseLevel: 73,
    mentalStage: {
      percentage: 87,
      sleep: 'Sleep well',
      cognitivePerformance: 'Mild/moderate cognitive overload'
    }
  }
]